### PR TITLE
added more labels for gopro 7

### PR DESCRIPTION
**Pull request by bright-light-in-the-night**
this has been tested with an extracted .bin from gopro 7

### CODE REVIEW

**Comment by stilldavid** [comment]
Totally! I've gotten unsubscribed from this repo for some reason so apologies for the delay, but going over some other changes now. Any chance you can send along a short sample video with GPS from the 7 someplace on Google Drive/Dropbox/etc..?

Thanks!

**Comment by dlisin** [comment]
@stilldavid Thank you!
Here is GH7 sample: https://www.dropbox.com/s/my702e7w5vipedx/GoPro_Hero7_Sample.MP4?dl=0

**Comment by robertdxyz** [comment]
@dlisin when I try with your file everything works as expected. When I use mine I get
```
Error reading telemetry file parsing time "6348225525520825": month out of range
```
Are you running the latest firmware? I am wondering if GoPro made a breaking change.

**Comment by dlisin** [comment]
@robertdolca 

My GH7 fw version is 01.61.00
But I do not think that this error is related to camera and/or fw version.

Yesterday I have faced exactly the same error with few videos from my GH6 camera.
It is seems  that GPMF data is corrupted somehow. Here is some debugging output:
```
Processing file: GH010245.MP4
time.Parse("060102150405", "5457900081260100"):  parsing time "5457900081260100": month out of range
time.Parse("060102150405", "5457900081260100"):  parsing time "5457900081260100": month out of range
time.Parse("060102150405", "6342425525554255"):  parsing time "6342425525554255": month out of range
time.Parse("060102150405", "6342425525554255"):  parsing time "6342425525554255": month out of range
time.Parse("060102150405", "5457900081260100"):  parsing time "5457900081260100": month out of range
time.Parse("060102150405", "5457900081260100"):  parsing time "5457900081260100": month out of range
time.Parse("060102150405", "5457900081260100"):  parsing time "5457900081260100": month out of range
time.Parse("060102150405", "1170000116255255"):  parsing time "1170000116255255": month out of range
time.Parse("060102150405", "500000146255255."):  parsing time "500000146255255.": month out of range

Processing file: /Users/dlisin/Temp/100GOPRO/GH020245.MP4
time.Parse("060102150405", "6343725525512200"):  parsing time "6343725525512200": month out of range
time.Parse("060102150405", "6338925525503000"):  parsing time "6338925525503000": month out of range
time.Parse("060102150405", "6338925525503000"):  parsing time "6338925525503000": month out of range
time.Parse("060102150405", "5457900081260100"):  parsing time "5457900081260100": month out of range
time.Parse("060102150405", "5457900081260100"):  parsing time "5457900081260100": month out of range
time.Parse("060102150405", "6339725525520625"):  parsing time "6339725525520625": month out of range
time.Parse("060102150405", "6339725525520625"):  parsing time "6339725525520625": month out of range
time.Parse("060102150405", "6340025525523000"):  parsing time "6340025525523000": month out of range
time.Parse("060102150405", "710000162255255."):  parsing time "710000162255255.": month out of range
time.Parse("060102150405", "710000162255255."):  parsing time "710000162255255.": month out of range
time.Parse("060102150405", "207000088255255."):  parsing time "207000088255255.": month out of range
time.Parse("060102150405", "207000088255255."):  parsing time "207000088255255.": month out of range
```

I will race a separate issue for this error

**Comment by robertdxyz** [comment]
@dlisin you are right. I tried the videos from another day and they all worked.
I was wondering if this is a camera issue but the Quick app seems to read the files properly, which leads me to believe it's something else.

**Comment by dlisin** [comment]
@robertdolca yes, Quick reads my files as well. May be it is just skips incorrect GPS dots. 
I will try to investigate this and prepare the fix

**Comment by dlisin** [comment]
I have raised #33 
@robertdolca can you please attach you BIN file to this ticket?

**Comment by robertdxyz** [comment]
Thank you. Added

**Pull request merged**
